# Generated by Django 5.2.1 on 2025-06-09 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_fornecedor_atividade_principal_fornecedor_bairro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='telefone',
        ),
        migrations.CreateModel(
            name='TelefoneFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='financeiro.fornecedor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
