# Generated by Django 5.2.1 on 2025-06-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_remove_fornecedor_telefone_telefonefornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(default='Sem telefone', max_length=20),
        ),
    ]
