# Generated by Django 5.2.1 on 2025-06-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_fornecedor_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='telefone',
        ),
    ]
